export const FETCH_FINANCIAL_REQUEST = 'FETCH_FINANCIAL_REQUEST';
export const FETCH_FINANCIAL_SUCCESS = 'FETCH_FINANCIAL_SUCCESS';
export const FETCH_FINANCIAL_FAILED = 'FETCH_FINANCIAL_FAILED';

export const FETCH_TOTAL_REQUEST = 'FETCH_TOTAL_REQUEST';
export const FETCH_TOTAL_SUCCESS = 'FETCH_TOTAL_SUCCESS';
export const FETCH_TOTAL_FAILED = 'FETCH_TOTAL_FAILED';
