export const FETCH_OPERATIONALS_REQUEST = 'FETCH_OPERATIONALS_REQUEST';
export const FETCH_OPERATIONALS_SUCCESS = 'FETCH_OPERATIONALS_SUCCESS';
export const FETCH_OPERATIONALS_FAILED = 'FETCH_OPERATIONALS_FAILED';
