export const FETCH_OTHER_INCOMES_REQUEST = 'FETCH_OTHER_INCOMES_REQUEST';
export const FETCH_OTHER_INCOMES_SUCCESS = 'FETCH_OTHER_INCOMES_SUCCESS';
export const FETCH_OTHER_INCOMES_FAILED = 'FETCH_OTHER_INCOMES_FAILED';
